# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
  - linux
  - osx

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

addons:
  apt:
    packages:
      - libssl1.0.0

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

latex: false

notifications:
  slack:
    secure: NL+dR4FTWkZnx+pXdDi7N8YmyxRn/4Y60uliRVb4g6swwzgOTMBWlGYrlFZUtNe5u3IYV5HFh331FucxnwfygpBo9Xb1GuuiIiPOjMUP00h+VUDqwkRAOHOP9oxV4SIAZukk7s4lCm7U/9GA/sz60NsIiciUjT+8c7wV3bmkkHE=


