# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

os:
- linux
- osx

<<<<<<< HEAD
=======
r:
- release
- oldrelease
- devel

>>>>>>> c9b292761f13b118f9d00cd6e70fdf71bc44412b
addons:
  apt:
    packages:
      - libssl1.0.0
